#!/usr/bin/python3

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Line graph of whole RMSD

data = np.loadtxt("rmsd_all.dat")
x = data[:,0]
y = data[:,1]

plt.title("RMSD of FpvAI and Pyocin S2")
plt.xlabel("Frame")  
plt.ylabel("RMSD Å") 
plt.ylim(0,10)		 
plt.plot(x, y, 'k-', linewidth=0.5)

plt.savefig("rmsd_all.png")
plt.show()


# Line graph of FpvAI RMSD

data = np.loadtxt("rmsd1.dat")
x = data[:,0]
y = data[:,1]

plt.title("RMSD of FpvAI")
plt.xlabel("Frame")
plt.ylabel("RMSD Å")
plt.ylim(0,10) 		
plt.plot(x, y, 'g-', linewidth=0.5, label="FpvAI")
plt.legend(loc="upper left")
plt.savefig("rmsd_FpvAI.png")
plt.show()



# Line graph of PyocinS2 RMSD

data = np.loadtxt("rmsd2.dat")
x = data[:,0]
y = data[:,1]

plt.title("RMSD of Pyocin S2")
plt.xlabel("Frame")
plt.ylabel("RMSD Å") 
plt.ylim(0, 10)		
plt.plot(x, y, 'b-', linewidth=0.5, label="PyoS2")
plt.legend(loc="upper left")
plt.savefig("rmsd_pyocinS2.png")
plt.show()

# Line graph of FpvAI and PyoS2 RMSD combined 

data = np.loadtxt("rmsd1.dat")
x = data[:,0]
y = data[:,1]
plt.title("RMSD of FpvAI and Pyocin S2 with Labile Domain")
plt.xlabel("Frame")  
plt.ylabel("RMSD Å") 
plt.plot(x, y, 'g-', linewidth=0.5, label="FpvAI")
plt.legend(loc="upper left")
plt.ylim(0,10)	


data = np.loadtxt("rmsd2.dat")
x = data[:,0]
y = data[:,1]		
plt.plot(x, y, 'b-', linewidth=0.5, label="PyoS2")
plt.legend(loc="upper left")
plt.savefig("combined.png")
plt.show()
