#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Apr 22 14:27:08 2021

@author: bs17yvt
"""

import numpy as np 
import matplotlib.pyplot as plt 

#on same plot

proteins = ["5ODW_FpvAI", "1BY3_FhuA", "1FEP_FepA", "1NQE_BtuB", "1PNZ_FecA", "1XKW_FptA", "2HDF_CirA", "2IAH_FpvA", "3CSL_HasR", "3EFM_FauA", "3FHH_ShuA", "4RDT_ZnuD", "5FOK_PiuA_Pa", "5FP1_PiuA_Ab", "5NEC_PiuD", "6E4V_FhuE", "6I97_FoxA", "6V81_YncD", "6BPM_Fiu"]

for protein in proteins:
    
    data = np.loadtxt(protein+"_res.txt")

    x = data[:,0]
    y = data[:,1]
    plt.figure() 
    plt.title(protein+" pI along Z axis", fontsize=16)
    plt.xlabel("Z Axis", fontsize=14)  
    plt.ylabel("Isoelectric Point", fontsize=14) 	
    plt.xlim(-25,50)
    #plt.xticks([i+5 for i in range (-25, 45)])
    plt.ylim(0,13)
    plt.plot(x, y, "o-", linewidth=1, label=protein)
    plt.legend(loc="upper right")
    plt.grid(":")
    plt.savefig(protein+".png")
    plt.show()
