#!/usr/bin/python3

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Line graph of FpvAI, PyoS2 and FptA RMSD combined for With plug 

data = np.loadtxt("rmsd_fpvai_WP.dat")
x = data[:,0]
y = data[:,1]
plt.title("RMSD of FpvAI and FptA with the Labile Domain")
plt.xlabel("Frame")  
plt.ylabel("RMSD Å") 
plt.plot(x, y, 'g-', linewidth=0.5, label="FpvAI")
plt.legend(loc="upper right")
plt.ylim(0,10)	


data = np.loadtxt("rmsd_fpta_WP.dat")
x = data[:,0]
y = data[:,1]	 
plt.plot(x, y, color="deeppink", linewidth=0.5, label="FptA")
plt.legend(loc="upper right")
plt.savefig("rmsd_fpta_fpvia_WP.png")
plt.show()

# Line graph of FpvAI and PyoS2 RMSD combined No plug 

data = np.loadtxt("fpvai_NP.dat")
x = data[:,0]
y = data[:,1]
plt.title("RMSD of FpvAI and FptA without the Labile Domain")
plt.xlabel("Frame")  
plt.ylabel("RMSD Å") 
plt.plot(x, y, 'g-', linewidth=0.5, label="FpvAI")
plt.legend(loc="upper right")
plt.ylim(0,10)	


data = np.loadtxt("rmsd_fpta_NP.dat")
x = data[:,0]
y = data[:,1]	 
plt.plot(x, y, color="deeppink", linewidth=0.5, label="FptA")
plt.legend(loc="upper right")
plt.savefig("rmsd_fpta_fpvia_NP.png")
plt.show()
